export const passwordsTypes = {
    GET_PASSWORDS_START: 'GET_PASSWORDS_START',
    GET_PASSWORDS_SUCCESS: 'GET_PASSWORDS_SUCCESS',
    GET_PASSWORDS_FAILURE: 'GET_PASSWORDS_FAILURE',
    CHANGE_FAVORITE: 'CHANGE_FAVORITE',
};
